import { InputTypeEnum } from "common/enums/inputTypeEnum";
import { PropertyEnum } from "common/enums/PropertyEnum";

export const INPUT_UI_MAP: Record<InputTypeEnum, PropertyEnum[]> = {
    [InputTypeEnum.Alert]: [
        PropertyEnum.placeholder,
        PropertyEnum.helpText,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
    ],

    [InputTypeEnum.Badge]: [
        PropertyEnum.placeholder,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
    ],
    [InputTypeEnum.Badges]: [
        PropertyEnum.placeholder,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Checkbox]: [
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden, 
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.size,
    ],

    [InputTypeEnum.Color]: [ 
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.size,
        PropertyEnum.pattern,
        PropertyEnum.prefix, 
    ],

    [InputTypeEnum.Date]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.DatetimeLocal]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.DropFiles]: [ 
        PropertyEnum.placeholder,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.size,
    ],

    [InputTypeEnum.Email]: [
        PropertyEnum.placeholder, 
        PropertyEnum.defaultValue, 
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.size,
        PropertyEnum.minLength,
        PropertyEnum.maxLength,
        PropertyEnum.pattern,
    ],

    [InputTypeEnum.File]: [ 
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.size,
    ],

    [InputTypeEnum.ForeignColumn]: [
        PropertyEnum.placeholder,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Html]: [ 
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size, 
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.HtmlEditor]: [ 
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size, 
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Image]: [ 
        PropertyEnum.placeholder,
        PropertyEnum.disabled,
        PropertyEnum.readonly,
        PropertyEnum.hidden,
        PropertyEnum.size,
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Month]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.MultipleDate]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.MultipleTime]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.Number]: [ 
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue, 
        PropertyEnum.disabled, 
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.prefix,
        PropertyEnum.suffix,
        PropertyEnum.min,
        PropertyEnum.max,
        PropertyEnum.helpText, 
    ],

    [InputTypeEnum.Password]: [
        PropertyEnum.placeholder,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.minLength,
        PropertyEnum.maxLength,
        PropertyEnum.helpText,
        PropertyEnum.pattern,
    ],

    [InputTypeEnum.QRCode]: [
        PropertyEnum.placeholder,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size, 
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Quarter]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.Radio]: [ 
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Range]: [ 
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.min,
        PropertyEnum.max,
        PropertyEnum.helpText, 
    ],

    [InputTypeEnum.RangeDate]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.RangeDatetimeLocal]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.RangeMonth]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.RangeQuarter]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.RangeWeek]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.RangeYear]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.Ratings]: [ 
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Select]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Tel]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.minLength,
        PropertyEnum.maxLength,
        PropertyEnum.helpText,
        PropertyEnum.pattern,
        PropertyEnum.prefix, 
    ],

    [InputTypeEnum.Text]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.prefix,
        PropertyEnum.suffix,
        PropertyEnum.size,
        PropertyEnum.minLength,
        PropertyEnum.maxLength,
        PropertyEnum.pattern,
    ],

    [InputTypeEnum.Textarea]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.minLength,
        PropertyEnum.maxLength,
        PropertyEnum.helpText,
        PropertyEnum.pattern,
    ],

    [InputTypeEnum.Time]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.URL]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.minLength,
        PropertyEnum.maxLength,
        PropertyEnum.helpText,
        PropertyEnum.pattern,
    ],

    [InputTypeEnum.Video]: [ 
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
    ],

    [InputTypeEnum.Week]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],

    [InputTypeEnum.Year]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.size,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.min,
        PropertyEnum.max,
    ],
    [InputTypeEnum.User]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.size,
        PropertyEnum.helpText,
    ],
    [InputTypeEnum.Icon]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.size,
    ],
    [InputTypeEnum.Parent]: [
        PropertyEnum.placeholder,
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.size,
    ],
    [InputTypeEnum.Switch]: [
        PropertyEnum.defaultValue,
        PropertyEnum.disabled,
        PropertyEnum.hidden,
        PropertyEnum.readonly,
        PropertyEnum.helpText,
        PropertyEnum.size,
    ],
};
