export enum InputTypeEnum {
    Alert = "Alert",
    Badge = "Badge",
    Badges = "Badges", 
    Checkbox = "Checkbox",
    Color = "Color",
    Date = "Date",
    DatetimeLocal = "DatetimeLocal",
    DropFiles = "DropFiles",
    Email = "Email",
    File = "File",
    ForeignColumn = "ForeignColumn",
    Html = "Html",
    HtmlEditor = "HtmlEditor",
    Image = "Image",
    Icon = "Icon",
    Month = "Month",
    MultipleDate = "MultipleDate",
    MultipleTime = "MultipleTime",
    Number = "Number",
    Password = "Password",
    Parent = "Parent",
    QRCode = "QRCode",
    Quarter = "Quarter",
    Radio = "Radio",
    Range = "Range",

    RangeDate = "RangeDate",
    RangeDatetimeLocal = "RangeDatetimeLocal",
    RangeMonth = "RangeMonth",
    RangeQuarter = "RangeQuarter",
    RangeWeek = "RangeWeek",
    RangeYear = "RangeYear",
    Ratings = "Ratings",
    Select = "Select",
    Switch = "Switch", 
    Tel = "Tel",
    Text = "Text",
    Textarea = "Textarea",
    Time = "Time",
    URL = "Url",
    User = "User",
    Video = "Video",
    Week = "Week",
    Year = "Year", 

    // Blockquote = "Blockquote",
    // Users = "Users",
    // Ribbon = "Ribbon",
    // Progress = "Progress",

    // Button = "Button",
    // Datetime = "Datetime",
    // Hidden = "Hidden",
    // Reset = "Reset",
    // Search = "Search",
    // Submit = "Submit",
}

export enum InputDateTypeEnum {
    Date = "Date",
    DatetimeLocal = "DatetimeLocal",
    Month = "Month",
    MultipleDate = "MultipleDate",
    MultipleTime = "MultipleTime",
    Quarter = "Quarter",
    
    RangeDate = "RangeDate",
    RangeDatetimeLocal = "RangeDatetimeLocal",
    RangeMonth = "RangeMonth",
    RangeQuarter = "RangeQuarter",
    RangeWeek = "RangeWeek",
    RangeYear = "RangeYear",
    Time = "Time",
    Week = "Week",
    Year = "Year", 
} 