namespace workgrid.Domain.Enums;

public enum InputTypeEnum
{
    Text = 0,
    Number = 1,
    Date = 2,
    Time = 3,
    DatetimeLocal = 4,
    Month = 5,
    Week = 6,
    Boolean = 7,
    Formula = 8,
    Reference = 9,
    Color = 10,
    Range = 11,
    Password = 12,
    Email = 13,
    URL = 14,
    File = 15,
    Tel = 16,
    Search = 17,
    Hidden = 18,
    Button = 19,
    Submit = 20,
    Reset = 21,
    Select = 22,
    Radio = 23,
    Checkbox = 24,
    Switch = 25,
    Textarea = 26,
    Url = 27,
    ForeignColumn = 28,
    HtmlEditor = 29,
    Image = 30,
    DropFiles = 31,
    Datetime = 32,

    MultipleTime = 33,
    Year = 34,
    Quarter = 35,



    RangeDate = 36,
    RangeWeek = 37,
    RangeMonth = 38,
    RangeQuarter = 39,
    RangeYear = 40,
    RangeDatetimeLocal = 41,
    MultipleDate = 42,


    Ratings = 43,
    Users = 44,
    Badge = 45,
    Ribbon = 46,
    Video = 47,
    QRCode = 48,
    Progress = 49,
    Blockquote = 50,
    Html = 51,
    Alert = 52,
    Badges = 53,
    User = 54,
    Icon = 55,
    Parent = 56,

}